
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.HBox hbox1;
	private global::Gtk.Label Nombre;
	private global::Gtk.Entry Nombre1;
	private global::Gtk.Button ButtonAplicar;
	private global::Gtk.Label labelSaludo;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(3));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.Nombre = new global::Gtk.Label ();
		this.Nombre.Name = "Nombre";
		this.Nombre.LabelProp = global::Mono.Unix.Catalog.GetString ("Nombre");
		this.hbox1.Add (this.Nombre);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.Nombre]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.Nombre1 = new global::Gtk.Entry ();
		this.Nombre1.CanFocus = true;
		this.Nombre1.Name = "Nombre1";
		this.Nombre1.Text = global::Mono.Unix.Catalog.GetString (" ");
		this.Nombre1.IsEditable = true;
		this.Nombre1.InvisibleChar = '•';
		this.hbox1.Add (this.Nombre1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.Nombre1]));
		w2.Position = 1;
		// Container child hbox1.Gtk.Box+BoxChild
		this.ButtonAplicar = new global::Gtk.Button ();
		this.ButtonAplicar.CanFocus = true;
		this.ButtonAplicar.Name = "ButtonAplicar";
		this.ButtonAplicar.UseUnderline = true;
		this.ButtonAplicar.Label = global::Mono.Unix.Catalog.GetString ("Aplicar");
		this.hbox1.Add (this.ButtonAplicar);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.ButtonAplicar]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.labelSaludo = new global::Gtk.Label ();
		this.labelSaludo.Name = "labelSaludo";
		this.labelSaludo.LabelProp = global::Mono.Unix.Catalog.GetString ("Hola Mundo");
		this.vbox1.Add (this.labelSaludo);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.labelSaludo]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 503;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
